fastlane_version "1.98.0"

require 'xcodeproj'

lane :generate_project do
  spm(
    command: "generate-xcodeproj",
    enable_code_coverage: true
  )
  project_path = '../Swarm.xcodeproj'
  project = Xcodeproj::Project.open(project_path)

# This force set of deployment targets is needed, because currently
# SPM generates test targets with latest deployment targets
# instead of using deployment targets for main package.
  project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = "10.12"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
      config.build_settings['TVOS_DEPLOYMENT_TARGET'] = "13.0"
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = "3.0"
    end
  end
  project.save()
end

lane :test_ios15 do
  generate_project
  scan(devices: ["iPhone 13 Pro Max (15.0)"])
end

lane :test_ios14 do
  generate_project
  scan(devices: ["iPhone 12 Pro (14.5)"])
end

lane :test_tvos15 do
  generate_project
  scan(device: "Apple TV 4K (15.0)")
end

lane :test_tvos14 do
  generate_project
  scan(device: "Apple TV 4K (14.5)")
end

lane :test_macos do
  generate_project
  scan(destination: "platform=macOS", disable_slide_to_type: false)
end

lane :test_linux do
  sh "swift test --enable-test-discovery"
end

lane :build_watchos do
  generate_project
  xcodebuild(
    build: true,
    destination: "OS=8.0,name=Apple Watch Series 6 - 44mm",
    scheme: 'Swarm-Package'
  )
end

lane :build_watchos_xcode12 do
  generate_project
  xcodebuild(
    build: true,
    destination: "OS=7.4,name=Apple Watch Series 6 - 44mm",
    scheme: 'Swarm-Package'
  )
end

lane :pod_lint do
  sh "bundle exec pod repo update"
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :generate_code_coverage do
  slather(
    proj: "Swarm.xcodeproj",
    scheme: "Swarm-Package",
    # arch: "x86_64",
    verbose: true,
    cobertura_xml: true
  )
end

lane :release do |params|
  version = params[:version]

  abort "You must specify a version in semver format." if version.nil? || version.scan(/\d+\.\d+\.\d+(-\w+\.\d+)?/).length == 0

  Dir.chdir("..") do

    puts "Updating podspec."
    filename = "Swarm.podspec"
    contents = File.read(filename)
    contents.gsub!(/s\.version\s*=\s"\d+\.\d+\.\d+(-\w+\.\d)?"/, "s.version      = \"#{version}\"")
    File.open(filename, 'w') { |file| file.puts contents }

    puts "Updating changelog."
    changelog_filename = "CHANGELOG.md"
    changelog = File.read(changelog_filename)
    changelog.gsub!(/# Next/, "# Next\n\n## [#{version}](https://github.com/DenTelezhkin/Swarm/releases/tag/#{version})")
    File.open(changelog_filename, 'w') { |file| file.puts changelog }

    puts "Comitting, tagging, and pushing."
    message = "Releasing version #{version}."
    sh "git add --all && git commit -m '#{message}'"
    sh "git tag #{version} -m '#{message}'"
    sh "git push --follow-tags"

    puts "Updating Specs repo"
    sh "bundle exec pod repo update"

    puts "Pushing to CocoaPods trunk."
    sh "bundle exec pod trunk push Swarm.podspec --allow-warnings"

    puts "Pushing as a GitHub Release."
    fastlane_require 'octokit'
    stripped_changelog = changelog.split(/^## /)[1].split("\n")[1..-1].join("\n").strip
    client = Octokit::Client.new(netrc: true)
    client.create_release('DenTelezhkin/Swarm',
                     version,
                     name: version,
                     body: stripped_changelog)
  end
end
