name: "CI"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Xcode-12:
    name: Xcode 12
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios14", "test_tvos14","test_macos", "build_watchos"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: List simulators
        run: xcrun simctl list
      - name: ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
      - name: Codecov
        uses: codecov/codecov-action@v1
  Xcode-11:
    name: Xcode 11
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    strategy:
      matrix:
        destination: ["test_ios13", "test_tvos13","test_macos", "build_watchos_xcode11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: List simulators
        run: xcrun simctl list
      - name: ${{ matrix.destination }}
        run: bundle exec fastlane ${{ matrix.destination }}
      - name: Codecov
        uses: codecov/codecov-action@v1
  cocoapods:
    name: Lint podspec
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: CocoaPods spec lint
        run: bundle exec fastlane pod_lint
  linux:
    name: "Test (Linux)"
    runs-on: ubuntu-16.04
    steps:
    - name: Swift 5.3 Docker Container
      uses: docker://swift:5.3-xenial
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec fastlane test_linux
